# Generated by Django 4.2.5 on 2023-09-17 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_клиента')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='комментарии')),
                ('year_birth', models.DateField(verbose_name='год рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_сообщения')),
                ('subject_letter', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body_letter', models.TextField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_рассылки')),
                ('name', models.CharField(max_length=50, verbose_name='наименование рассылки')),
                ('time_from', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('time_by', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('period', models.CharField(choices=[('Каждый день', 'Dayly'), ('Каждую неделю', 'Weekly'), ('Каждый месяц', 'Monthly')], max_length=50, verbose_name='Период рассылки')),
                ('status', models.CharField(default='создана', max_length=50, verbose_name='Статус рассылки')),
                ('customers', models.ManyToManyField(to='mailing.client', verbose_name='Список клиентов')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Письмо для рассылки')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time_date', models.DateTimeField(auto_now=True, verbose_name='время последней попытки')),
                ('status', models.CharField(max_length=150, verbose_name='статус попытки')),
                ('server_response', models.CharField(max_length=150, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.messagesettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
    ]
