# Generated by Django 4.2.5 on 2023-09-13 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_клиента')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='комментарии')),
                ('year_birth', models.DateField(verbose_name='год рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MessageSattings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_рассылки')),
                ('time_massage', models.DateTimeField(verbose_name='время рассылки')),
                ('status', models.CharField(verbose_name='статус рассылки')),
                ('frequency', models.DateTimeField(verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id_сообщения')),
                ('subject_letter', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body_letter', models.TextField(blank=True, null=True, verbose_name='тело письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='клиент')),
                ('message_sattings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.messagesattings', verbose_name='настройки рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
