# Generated by Django 4.2.5 on 2023-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logi',
            name='server_response',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ сервера'),
        ),
    ]
