# Generated by Django 4.2.5 on 2023-09-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_logi_server_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logi',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.messagesettings', verbose_name='ID рассылки'),
        ),
    ]
