# Generated by Django 4.2.5 on 2023-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_messagesettings_last_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesettings',
            name='last_dispatch_date',
            field=models.DateField(default=None, verbose_name='дата последней отправки'),
        ),
    ]
