# Generated by Django 4.2.5 on 2023-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_messagesettings_last_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesettings',
            name='last_dispatch_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата последней отправки'),
        ),
    ]
