# Generated by Django 4.2.5 on 2023-10-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_message_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesettings',
            name='status',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
